services:
  # Backend
  - type: web
    name: mon-api-backend
    rootDir: Le-Format/backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: PORT
        value: "8000"

static:
  # Frontend
  - name: mon-frontend-react
    rootDir: Le-Format/frontend
    buildCommand: "npm install && npm run build"
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html