services:
  # Backend
  - type: web
    name: mon-api-backend
    rootDir: Le-Format/backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: PORT
        value: "8000"

  # Frontend
  - type: web
    name: mon-frontend-react
    rootDir: Le-Format/frontend
    runtime: node
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s dist"
    envVars:
      - key: PORT
        value: "3000"